#!/bin/bash
case "$1" in
  list)
cat <<'OUT'
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *494.4 GB   disk0
   1:             Apple_APFS_ISC Container disk1         524.3 MB   disk0s1
   2:                 Apple_APFS Container disk3         494.4 GB   disk0s2
   3:        Apple_APFS_Recovery Container disk2         5.4 GB     disk0s3

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +494.4 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD            10.2 GB    disk3s1
   2:              APFS Snapshot com.apple.os.update-    10.2 GB    disk3s1s1
   3:                APFS Volume Preboot                 6.9 GB     disk3s2
   4:                APFS Volume Recovery                1.0 GB     disk3s3
   5:                APFS Volume Data                    291.4 GB   disk3s5
   6:                APFS Volume VM                      1.1 GB     disk3s6
OUT
    ;;
  info)
cat <<'OUT'
   Device Identifier:         disk3s5
   Device Node:               /dev/disk3s5
   Whole:                     No
   Part of Whole:             disk3

   Volume Name:               Macintosh HD - Data
   Mounted:                   Yes
   Mount Point:               /System/Volumes/Data

   File System Personality:   APFS
   Type (Bundle):             apfs
   Owners:                    Enabled

   OS Can Be Installed:       No
   Media Type:                Generic
   Protocol:                  Apple Fabric
   SMART Status:              Verified
OUT
    ;;
  *) printf 'Usage: diskutil [quiet] <verb> <options>, where <verb> is as follows:\n\n     list                (List the partitions of a disk)\n     info | information  (Get information on a specific disk or partition)\n' >&2; exit 1 ;;
esac
